"""Application constants."""

# HTTP Status codes
OK_CODE = 200
CREATED_CODE = 201
BAD_REQUEST_CODE = 400
FORBIDDEN_CODE = 403
NOT_FOUND_CODE = 404
CONFLICT_CODE = 409

# String field lengths
EMAIL_MAX_LENGTH = 255
STRING_MAX_LENGTH = 255
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 40
TOKEN_LENGTH = 32

# Wallet constants
MAX_WALLETS_PER_USER = 3
